# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=90),
        ),
    ]
